accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

password_safe/urls.py
from django.urls import path
from .views import (
    AccountCreateView,
    HomePageView,
    SiteDetailView,
    SiteDeleteView,
    SiteEditView,
    SiteCreateView,
    AccountDeleteView,
    AccountEditView,
    AccountCreateView,
)

urlpatterns = [
    path("<slug:slug>/new_account/", AccountCreateView.as_view(), name="account_new"),
    path(
        "<slug:slug>/<slug:slug_field>/edit/",
        AccountEditView.as_view(),
        name="account_edit",
    ),
    path(
        "<slug:slug>/<slug:slug_field>/delete/",
        AccountDeleteView.as_view(),
        name="account_delete",
    ),
    path("new_site/", SiteCreateView.as_view(), name="site_new"),
    path("<slug:slug>/edit/", SiteEditView.as_view(), name="site_edit"),
    path("<slug:slug>/delete/", SiteDeleteView.as_view(), name="site_delete"),
    path("<slug:slug>/", SiteDetailView.as_view(), name="site_detail"),
    path("", HomePageView.as_view(), name="home"),
]

password_safe_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("password_safe.urls")),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    age = models.PositiveBigIntegerField(blank=True, null=True)

password_safe/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.template.defaultfilters import slugify


class Site(models.Model):
    siteName = models.CharField(max_length=200)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    slug = models.SlugField(null=False, unique=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.siteName

    def get_absolute_url(self):
        return reverse("site_detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            slug_str = "%s %s" % (self.siteName, self.author)
            self.slug = slugify(slug_str)
        super(Site, self).save()


class Account(models.Model):
    site_name = models.ForeignKey(Site, on_delete=models.CASCADE)
    username = models.CharField(max_length=140)
    password = models.CharField(max_length=50)
    slug_field = models.SlugField(null=False, unique=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("home")

    def save(self, *args, **kwargs):
        if not self.slug_field:
            self.slug_field = slugify(self.username)
        return super().save(*args, **kwargs)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = (
            "username",
            "email",
            "age",
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = (
            "username",
            "email",
            "age",
        )

password_safe/forms.py
from django import forms
from .models import Accounts


class UserForm(forms.ModelForm):
    class Meta:
        model = Accounts
        widgets = {
            "password": forms.PasswordInput(),
        }

accounts/views.py
from django.views.generic import CreateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = "registration/signup.html"
    success_url = reverse_lazy("login")

password_safe/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import DeleteView, UpdateView
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse
from .models import Account, Site


class HomePageView(ListView):
    model = Site
    template_name = "home.html"

    def get_queryset(self):
        try:
            return Site.objects.filter(author=self.request.user)
        except:
            return HttpResponse("Login please!")


class SiteDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Site
    template_name = "site_detail.html"

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class SiteDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Site
    template_name = "site_delete.html"
    success_url = reverse_lazy("home")

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class SiteEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Site
    template_name = "site_edit.html"
    fields = ("siteName",)

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class AccountDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Account
    template_name = "account_delete.html"
    slug_field = "slug_field"
    slug_url_kwarg = "slug_field"
    success_url = reverse_lazy("home")


class AccountEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Account
    template_name = "account_edit.html"
    fields = (
        "username",
        "password",
    )
    slug_field = "slug_field"
    slug_url_kwarg = "slug_field"


class SiteCreateView(LoginRequiredMixin, CreateView):
    model = Site
    template_name = "site_new.html"
    fields = ("siteName",)

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "account_new.html"
    fields = (
        "site_name",
        "username",
        "password",
    )

templates/account_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h2>Delete</h2>
<p>Are you sure you want to delete "{{ object.site_name }}"
   account with username "{{ object.username }}"</p>
<form method="post">{% csrf_token %}
  {{ form|crispy }}
  <button type="submit">Delete</button>
</form>
{% endblock content %}

templates/account_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h2>Edit</h2>
<hr>
<form method="post">{% csrf_token %}
  {{ form|crispy }}
  <button type="submit">Update</button>
</form>
{% endblock content %}

templates/account_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h2>New account</h2>
<form  method="post">{% csrf_token %}
  {{ form|crispy }}
  <input type="submit" value="Submit">
</form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Password Safe App</title>
  </head>
  <body>
    <header>
        <h1><a href="{% url 'home' %}">Password Safe</a></h1>
    </header>
    <main>
      {% block content %}
      {% endblock content %}
    </main>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
<p>Hi {{ user.username }}</p>
<a href="{% url 'site_new' %}">New Site</a>
<br>
<br>
  <a href="{% url 'logout' %}">logOut</a>
  {% if object_list %}
    {% for site in object_list %}
    <ul>
      <li><a href="{% url 'site_detail' site.slug %}">{{ site.siteName }}</a></li>
    </ul>
    {% endfor %}
  {% else %}
      <p>You have no sites saved.</p>
  {% endif %}

{% else %}
<h2>Welcome to password safe.</h2>
<hr>
<a href="{% url 'login' %}">LogIn</a> |
<a href="{% url 'signup' %}">SignUp</a>
{% endif %}
{% endblock content %}

templates/site_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h2>Delete</h2>
<p>Are you sure you want to delete "{{ object.siteName }}"</p>
<p>All accounts saved to this site would be deleted too.</p>
<form method="post">{% csrf_token %}
  {{ form|crispy }}
  <button type="submit">Delete</button>
</form>
{% endblock content %}

templates/site_detail.html
{% extends 'base.html' %}
{% block content %}
<h2>{{ object.siteName }}</h2>
<a href="{% url 'account_new' object.slug %}"><button type="button" >New Account</button></a>
<hr>
{% for username in object.account_set.all %}
<p>Username: {{ username.username }}</p>
<p>Password: {{ username.password }}</p>
<p><a href="{% url 'account_edit' object.slug username.slug_field %}"><button type="button">Edit account</button></a>
<a href="{% url 'account_delete' object.slug username.slug_field %}"><button type="button">Delete account</button></a></p>
<hr>
{% endfor %}
<p><a href="{% url 'site_delete' object.slug %}"><button type="button">Delete site</button></a>
  <a href="{% url 'site_edit' object.slug %}"><button type="button">Edit site</button></a></p>
{% endblock content %}

templates/site_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h2>Edit</h2>
<hr>
<form method="post">{% csrf_token %}
  {{ form|crispy }}
  <button type="submit">Update</button>
</form>
{% endblock content %}

templates/site_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h2>New Site</h2>
<form  method="post">{% csrf_token %}
  {{ form|crispy }}
  <input type="submit" value="Submit">
</form>
{% endblock content %}